### ISSUE TITLE
Determine linear drift correction gap at calibration events

### ISSUE THREAD

**Issue by tannerlex** [AmberSJones/PyHydroQC#91]
add a function to determine the sensor output difference after calibration

**Comment by tannerlex** [comment]
given a datetime window, look for the greatest difference or for 2 distinct clusters or ...

**Comment by AmberSJones** [comment]
this is implemented in the find_gap function, which finds the greatest difference within a window of a calibration. Clustering based on level and time is another possible approach that could be attempted at some point.
